### ISSUE TITLE
Neutron Failing To Download Multiple Programs + Suggestions

### ISSUE THREAD

**Issue by Bloopy442** [SkylerWallace/ATOM#3] opened 2023-12-10 22:27 UTC
![IMG_2199](https://github.com/SkylerWallace/ATOM/assets/152941822/ada0c70f-b7a4-4fd1-88c0-ce153b53edd5)
![IMG_2200](https://github.com/SkylerWallace/ATOM/assets/152941822/daacbe5f-e777-414f-be91-d83a52c07c17)
![IMG_2201](https://github.com/SkylerWallace/ATOM/assets/152941822/66f720a3-cb81-413b-b4d4-13b8da66ed55)

I know these are potato photos (screenshots) from my phone but I was too lazy to manually screenshot on the clients PC, save, swap to a flash drive then upload here so these will have to do! 

These are local accounts, too, not Microsoft if that helps (as we do for all new PC setups).

For me, I mostly use Neutron from ATOM for pretty much everything and I REALLY want to like/use it (for convenience purposes, obv) but for whatever reason these issues above happen on 95% of the computers (both Windows 10 and 11). Whenever I select the programs I want to download and click run it seems to only install the first one (SOMETIMES) and then fails for all the rest of them. It has only ever worked for me on maybe two? computers (out of at least 35+ before I started to give up on it) since I first started trying to use it about a month ago (I even updated to 2.6 to see if that fixed the issue, it didn't). On my personal Windows 11 PC at home, works fine, at work on multiple clients PC's it seems to always have the same issue. There used to be an option for downloading Winget/Chocolatey but it was removed in 2.6 (but this still didn't fix the issue). Sometimes it'd try install using both Winget/Chocolatey and they'd fail cause they'd try to both install at the same time, had that issue happen a couple times. 

The Dark Mode i've noticed when it's enabled messes the colors up a bit [the task bar I think gets messed up as well] (forgot to take a screenshot of this) and having Transparency turned off seems to fix the issue most of the time. You can't see the cursor on the URL address in browsers as well, like if you were to try to hover your mouse over the URL to type a website out, it's transparent so you can't see it. It'd be convenient to have it turned off, too (or the option to as well w/ dark mode). 

I don't think the Timezone area was working for me either.

Suggestions: 

If you could add the "Geek Squad Support" Logo .exe for us to have an option to download that brings them to the remote help link on our website that'd be ideal, too (screenshots below as examples) it'll automatically detect/bold which is installed to clear/reset: 
![image](https://github.com/SkylerWallace/ATOM/assets/152941822/8aea3652-09bb-4fd0-a32d-39a881212894)
![image](https://github.com/SkylerWallace/ATOM/assets/152941822/fd6eecb6-a0b3-481d-aa64-0be5b2fe0ed0)
![image](https://github.com/SkylerWallace/ATOM/assets/152941822/76921bcf-4af0-42ac-8b9d-0f8796eab78d)

If you could add "Reset" (clearing web browser integrity data) in all browsers like Edge, Chrome, Firefox etc as an option in Neutron that too would be awesome as well (Screenshot below for what i'm talking about). Where we can just select Edge, Chrome, Firefox etc (whatever the client uses) to have them be reset (under it's own tab). 
![image](https://github.com/SkylerWallace/ATOM/assets/152941822/172731d5-80be-4442-a65a-e2ee3a8d0064)
![image](https://github.com/SkylerWallace/ATOM/assets/152941822/6b5ed0c3-ddde-47f8-9c96-aaaace9d95f1)

This helps with clearing out bad extensions, search browsers etc in all of their browsers (very useful). 

If you could add a DISM command button under the SFC Scannnow button, that'd be nice to have too.
And/or the option to select both. 

I might be missing some things, I wanted to post ALL of the issues I had and some suggestions a few weeks back but I got busy but I hope some of this helps. Love the work so far, truly! and I really hope you can fix some of these issues and plaster a bunch of useful options all in one spot for quick and ease of use. 

A time/date and start/complete of what all was done during one sitting of use of ATOM would be nice, too.
To know what installed, what failed, how long it took etc. 

![image](https://github.com/SkylerWallace/ATOM/assets/152941822/0c5617f8-0496-42a3-a725-b74eca2ea977)

**Comment by SkylerWallace** [comment] 2023-12-11 04:02
Hello Bloopy,

Thank you for the issue report.  When submitting issues in the future, I recommend to break them up into separate individual issues so I can mark them complete individually when they're resolved.  Also, for suggestions I recommend using "Pull Request".

> For me, I mostly use Neutron from ATOM for pretty much everything and I REALLY want to like/use it (for convenience purposes, obv) but for whatever reason these issues above happen on 95% of the computers (both Windows 10 and 11). Whenever I select the programs I want to download and click run it seems to only install the first one (SOMETIMES) and then fails for all the rest of them. It has only ever worked for me on maybe two? computers (out of at least 35+ before I started to give up on it) since I first started trying to use it about a month ago (I even updated to 2.6 to see if that fixed the issue, it didn't). On my personal Windows 11 PC at home, works fine, at work on multiple clients PC's it seems to always have the same issue. There used to be an option for downloading Winget/Chocolatey but it was removed in 2.6 (but this still didn't fix the issue). Sometimes it'd try install using both Winget/Chocolatey and they'd fail cause they'd try to both install at the same time, had that issue happen a couple times.

It might help to understand how Neutron works.  Neutron uses up to 4 install methods to install a program: winget, chocolatey, direct URL, and mirror URL.  If Neutron detects that winget or chocolatey are not installed when running, it _should_ install both of them.  This is the reason why the options to install winget and chocolatey were removed, it _should_ do this automatically.  However, I have noticed that this method is not 100% reliable and I will work at addressing this soon.  For now, if you perform Microsoft Store updates (this occurs when running the Trifecta plugin) then this should update the App Installer package which will install winget.  Doing this will ensure all winget installations work properly.

Also, Chrome specifically has that "Unknown install error".  The direct URL to download the offline installer to Chrome is here:
https://dl.google.com/dl/chrome/install/ChromeStandaloneSetup64.exe

If you download via a web browser, the installer works properly.  However, Neutron downloads the installer via command line.  This method was working but within the last month Google changed the installer to require being downloaded via web browser.  I will resolve this soon by using a different URL.

> The Dark Mode i've noticed when it's enabled messes the colors up a bit [the task bar I think gets messed up as well] (forgot to take a screenshot of this) and having Transparency turned off seems to fix the issue most of the time. You can't see the cursor on the URL address in browsers as well, like if you were to try to hover your mouse over the URL to type a website out, it's transparent so you can't see it. It'd be convenient to have it turned off, too (or the option to as well w/ dark mode).

Dark Mode in Neutron works properly, the issue is that it doesn't update all the UI elements.  Restarting the computer will apply Dark Mode to all appropriate elements.  I will look at finding a method for getting the UI to update without needing to start the computer.

> I don't think the Timezone area was working for me either.

Timezone has been working for me but I have seen it have issues a handful of times.  I will take a look at this.

> If you could add the "Geek Squad Support" Logo .exe for us to have an option to download that brings them to the remote help link on our website that'd be ideal, too (screenshots below as examples) it'll automatically detect/bold which is installed to clear/reset

ATOM would fall under the category of "unapproved tools" and thus isn't for Geek Squad usage.  However, implementing something like this would be trivial.  All of ATOM is modular; it's MEANT for the user to tweak and add functionality.  If you have questions about how to add features or plugins, let me know.  In the future I plan to make a video showing how to add plugins to ATOM.

> If you could add "Reset" (clearing web browser integrity data) in all browsers like Edge, Chrome, Firefox etc as an option in Neutron that too would be awesome as well (Screenshot below for what i'm talking about). Where we can just select Edge, Chrome, Firefox etc (whatever the client uses) to have them be reset (under it's own tab).

The Debloat plugin has a more advanced version of this already.  I do not recommend whole-sale resetting web browsers as this clears cookies which means it will log the user out of ALL websites as well as removing all plugins.

> If you could add a DISM command button under the SFC Scannnow button, that'd be nice to have too.  And/or the option to select both.

I will consider this.  I was thinking about having a better solution to SFC and DISM altogether.  In the mean time, you are more than welcome to add this feature for your own personal use.  It would be simple as placing a DISM batch script within ATOM/Dependencies/Neutron/Shortcuts.  Again, ATOM was made to be modular and simple to expand upon.

> A time/date and start/complete of what all was done during one sitting of use of ATOM would be nice, too.
> To know what installed, what failed, how long it took etc.

There is currently a plugin called "ATOM Notes" which is used to take notes on a computer; it is similar to MRI HUD.  I was contemplating having it automatically add notes whenever a plugin launches or runs.

**Comment by SkylerWallace** [comment] 2023-12-12 00:40
Everything has been addressed in this [commit](https://github.com/SkylerWallace/ATOM/commit/dd6601f4b1c55e8104c7602cf503c98cc77ce8ab).

Spotify still does not install because it requires being installed as a standard user.  Unfortunately, there is no simple solution for this.  I will look into methods but it will not be a priority at this time.

Marking this issue as closed.

**Closed by SkylerWallace** 2023-12-12 00:40 UTC
